# Site settings
title: Diary of a Wimpy Coder
header-img: img/home-bg.png
email: ajoshow@sas.upenn.edu
copyright_name: andyjoshowitz
description: > # this means to ignore newlines until "baseurl:"
  A journey through the world of programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  andyjoshowitz
learn_profile: andyjoshowitz
email_username: ajoshow@sas.upenn.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
